services:

    api:
      build:
        context: ./services/api
        dockerfile: Dockerfile
      environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - DB_HOST=mysql
        - API_PORT=${API_PORT}
      depends_on:
        mysql:
          condition: service_healthy
      networks:
        - app-network

    mysql:
      build:
        context: ./services/mysql
        dockerfile: Dockerfile
      ports:
        - "${MYSQL_PORT}:3306"
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
        interval: 10s
        timeout: 10s
        retries: 15
      environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      networks:
        - app-network

networks:
  app-network:
    name: app-network
    driver: bridge



